{
response: {"error":false,"errorMsg":null,"data":{"html":"
<div id=\"finishNowDialog\">\n<p>The following orders will be completed instantly:<\ /p>\n\n
            <h5>Building orders:<\ /h5>\n
                    <ul>\n\t\t\t\t<?php foreach ($building->buildArray as $jobs) {
                                        if ($jobs['type'] != 25 && $jobs['type'] != 26 && $jobs['type'] != 40) { ?>
                        <li>\n\t\t\t\t<span>\n\t\t\t\t<?php echo constant('B' . $jobs['type']); ?>\t\t\t\t<\ /span>\n\t\t\t\t\t\t\t\t\t<span class=\"lvl\">\n\t\t\t\t\t<?php echo LVL . " " . $jobs['level']; ?>\t\t\t\t\t<\ /span>\n\t\t\t\t\t\t\t<\ /li><?php }
                                                                                                                                                                                                                                                    } ?>\n\t<\ /ul>\n<div class=\"buttonWrapper\">\n\t<button type=\"submit\" value=\"Redeem\" id=\"button526f6a538e698\" class=\"gold \" title=\"Complete all construction orders and research immediately.\" coins=\"2\">\n\t<div class=\"button-container addHoverClick\">\n\t\t<div class=\"button-background\">\n\t\t\t<div class=\"buttonStart\">\n\t\t\t\t<div class=\"buttonEnd\">\n\t\t\t\t\t<div class=\"buttonMiddle\">
                                                                                <\ /div>\n\t\t\t\t<\ /div>\n\t\t\t<\ /div>\n\t\t<\ /div>\n\t\t<div class=\"button-content\">Redeem<img src=\"img\/x.gif\" class=\"goldIcon\" alt=\"\" \ /><span class=\"goldValue\">2<\ /span>
                                                                                                            <\ /div>\n\t<\ /div>\n<\ /button>\n<script type=\"text\/javascript\">\n\twindow.addEvent('domready', function()\n\t{\n\tif($('button526f6a538e698'))\n\t{\n\t\t$('button526f6a538e698').addEvent('click', function ()\n\t\t{\n\t\t\twindow.fireEvent('buttonClicked', [this, {\"type\":\"submit\",\"value\":\"Redeem\",\"name\":\"\",\"id\":\"button526f6a538e698\",\"class\":\"gold \",\"title\":\"Complete all construction orders and research immediately.\",\"confirm\":\"\",\"onclick\":\"\",\"coins\":2,\"wayOfPayment\":{\"featureKey\":\"finishNow\",\"context\":\"\"}}]);\n\t\t});\n\t}\n\t});\n<\/script>\n<\/div>\n<\/div>"}}
}